version: "3"
services:
    # Database
    db:
        image: mysql:8.0.33-oracle
        container_name: db
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        env_file: .env
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
        networks:
            - wpNetwork


networks:
    wpNetwork:
volumes:
    wordpress:
    db_data: