version: "3"
services:
    # Database
    db:
        image: mysql:8.0.33-oracle
        container_name: db
        volumes:
            - db_data:/var/lib/mysql
        restart: unless-stopped
        env_file: .env
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
        networks:
            - wpNetwork
    # WordPress
    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        container_name: wordpress
        ports:
            - "80:80"
        restart: always
        volumes:
            - wordpress:/var/www/html
            #- ./themes/Divi:/var/www/html/wp-content/themes/Divi
            #- ./plugins/sucuri-scanner:/var/www/html/wp-content/plugins/sucuri-scanner
        env_file: .env
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: $MYSQL_DATABASE
            WORDPRESS_DB_USER: $MYSQL_USER
            WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
        networks:
            - wpNetwork
    # WEB SERVER

networks:
    wpNetwork:
volumes:
    wordpress:
    db_data: